# food_records_fn = formatted file of all diet records, must contain FoodID and grams columns
# food_record_id = column name of identifier separating your diet records (e.g. subjectid, sampleid, etc.)
# food_taxonomy_fn = taxonomy file generated by make.food.tree
# output_fn = output file name of your food otu table
make.dhydrt.per.kcal.otu <- function(food_records_fn, food_record_id, food_taxonomy_fn, output_fn)
{
    # read everything in as a character to preserve numeric food codes and IDs
    diet <- read.table(food_records_fn, header = TRUE, sep="\t", colClasses="character", quote="", strip.white=T)
    diet$FoodAmt <- as.numeric(diet$FoodAmt)
    diet$KCAL <- as.numeric(diet$KCAL)
    diet$MOIS <- as.numeric(diet$MOIS)
    
    # make new variable dhydrated grams per kcal
    diet$dgpk <- (diet$FoodAmt - diet$MOIS)/diet$KCAL

    # sum total grams of each food eaten within a record
    cdiet <- aggregate(diet$dgpk, by=list(diet[,food_record_id], diet$FoodID), FUN=sum)
    colnames(cdiet) <- c(food_record_id, "FoodID", "dgpk")

    cdiet.w <- reshape(cdiet, timevar = "FoodID", idvar = food_record_id, direction = "wide")
    cdiet.w[is.na(cdiet.w)] <- 0
    rownames(cdiet.w) <- cdiet.w[,1] # make record_ids the rownames
    cdiet.w <- cdiet.w[,-1]    
    colnames(cdiet.w) <- gsub("dgpk.", "", colnames(cdiet.w)) #rename column names to FoodIDs only
    t.cdiet.w <- t(cdiet.w)
    
    food.taxonomy <- read.table(food_taxonomy_fn, sep="\t", colClasses="character", quote="", header=T, row=1)
    
    dgpk.otu <- merge(t.cdiet.w, food.taxonomy, by=0)
    
    # let's get rid of the FoodIDs and replace it with the food tree leaf names
    rownames(dgpk.otu) <- dgpk.otu[,"Main.food.description"]
    remove.col.ix <- which(colnames(dgpk.otu) %in% c("Main.food.description", "Row.names"))
    dgpk.otu <- dgpk.otu[,-remove.col.ix]
    
    #drop rows with infinate values
    inf.vals <- which(rowSums(dgpk.otu[,-ncol(dgpk.otu)]) == Inf)
    dgpk.otu <- dgpk.otu[!(rownames(dgpk.otu) %in% names(inf.vals)),]
 
    cat("#FOODID\t", file=output_fn)
    write.table(dgpk.otu, output_fn, sep = "\t", quote = F, append=TRUE)
    
    invisible(dgpk.otu)
}

