#making make.food.otu.R commandline runable

#!/usr/bin/env Rscript

#TO DO:figure out what packages need to be uploaded
suppressPackageStartupMessages(require())

usage = 'make.food.otu.r will change your life'

option_list = list(
  make_option(c('-a', '--food_records_fn'),
              help= 'Formatted file of all diet records, must contain FoodID and grams columns',
              default = NA, type='character'),
  make_option(c('-b', '--food_record_id'),
              help= 'Column name of identifier separating your diet records',
              default= NA, type='character'),
  make_option(c('-c', 'food_taxonomy_fn'),
              help = 'Taxonomy file generated by make.food.tree',
              default= NA, type='character'),
  make_option(c('-o', '--output'),
              help = 'Direct the output file to local folder',
              default = NA, type='character')
)

opt = parse_args(OptionParser(usage=usage, option_list=option_list))

if (is.na(opt$food_records_fn) | is.na(opt$food_record_id) | is.na(opt$food_taxonomy_fn) | (is.na(opt$output_fn))) {
  stop('Missing required files')
}

#probably need to change up the names
food_records_fn <- opt$food_records_fn
food_record_id <- opt$food_record_id
food_taxonomy_fn <- opt$food_taxonomy_fn
output_fn <- opt$output_fn

#just Abby's code copy and pasted
make.food.otu <- function(food_records_fn, food_record_id, food_taxonomy_fn, output_fn)
{
  # read everything in as a character to preserve numeric food codes and IDs
  diet <- read.table(food_records_fn, header = TRUE, sep="\t", colClasses="character", quote="", strip.white=T)
  diet$FoodAmt <- as.numeric(diet$FoodAmt)
  
  # sum total grams of each food eaten within a record
  cdiet <- aggregate(diet$FoodAmt, by=list(diet[,food_record_id], diet$FoodID), FUN=sum)
  colnames(cdiet) <- c(food_record_id, "FoodID", "total.grams")
  
  cdiet.w <- reshape(cdiet, timevar = "FoodID", idvar = food_record_id, direction = "wide")
  cdiet.w[is.na(cdiet.w)] <- 0
  rownames(cdiet.w) <- cdiet.w[,1] # make record_ids the rownames
  cdiet.w <- cdiet.w[,-1]    
  colnames(cdiet.w) <- gsub("total.grams.", "", colnames(cdiet.w)) #rename column names to FoodIDs only
  t.cdiet.w <- t(cdiet.w)
  
  food.taxonomy <- read.table(food_taxonomy_fn, sep="\t", colClasses="character", quote="", header=T, row=1)
  
  food.otu <- merge(t.cdiet.w, food.taxonomy, by=0)
  
  # let's get rid of the FoodIDs and replace it with the food tree leaf names
  rownames(food.otu) <- food.otu[,"Main.food.description"]
  remove.col.ix <- which(colnames(food.otu) %in% c("Main.food.description", "Row.names"))
  food.otu <- food.otu[,-remove.col.ix]
  
  cat("#FOODID\t", file=output_fn)
  write.table(food.otu, output_fn, sep = "\t", quote = F, append=TRUE)
  
  invisible(food.otu)
}

